# Generated by Django 2.1.5 on 2019-06-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auther_info',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auther_info',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
