# Generated by Django 2.1.5 on 2019-06-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0002_auto_20190612_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auther',
            name='age',
        ),
        migrations.AlterField(
            model_name='auther_info',
            name='addr',
            field=models.CharField(default='null', max_length=86),
        ),
        migrations.AlterField(
            model_name='auther_info',
            name='age',
            field=models.IntegerField(default='null'),
        ),
        migrations.AlterField(
            model_name='auther_info',
            name='birthday',
            field=models.DateField(default='null'),
        ),
        migrations.AlterField(
            model_name='auther_info',
            name='telephone',
            field=models.BigIntegerField(default='null'),
        ),
    ]
