# Generated by Django 2.1.5 on 2019-06-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book1', '0003_auto_20190612_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
